### ISSUE TITLE
switch combinations

### ISSUE THREAD

**Issue by rit001** [cloudymax/pxeless#9]
I hope you don't mind me raising issues like this as I don't have the time or really the skills to do direct modifications and pull requests.

Your script has a problem when trying to use the -s (source) switch as you also need to define the -n (code-name) switch as the script still tries to run function latest_release which will fail on the first curl as it can not retrieve a valid file without a code name being provided.

**Comment by cloudymax** [comment]
No worries, I appreciate you taking the time to report bugs.`

I was able to re-create the issue and will push a fix as soon as I'm able.

**Comment by cloudymax** [comment]
Looks like I'm able to get the desired behavior by making changes to the way I detect if an images is legacy(isolinux) vs el torito. Instead of doing a greater/less comparison on the release number, i'll just check fore the presence of isolinux in the extracted iso itself, and if its there, it's marked as legacy. This seems to let everything build properly.
